# Generated by Django 4.2 on 2026-01-27 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lokasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('keluhan', models.TextField()),
                ('prioritas', models.CharField(choices=[('rendah', 'Rendah'), ('sedang', 'Sedang'), ('tinggi', 'Tinggi'), ('kritis', 'Kritis')], max_length=20)),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('proses', 'Proses'), ('selesai', 'Selesai'), ('ditutup', 'Ditutup')], default='baru', max_length=20)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelapor', to=settings.AUTH_USER_MODEL)),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petugas', to=settings.AUTH_USER_MODEL)),
                ('ruangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lokasi.ruangan')),
            ],
        ),
    ]
