# Generated by Django 4.2 on 2026-01-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriTiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tiket')),
            ],
        ),
    ]
