# Generated by Django 4.2 on 2026-02-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_historitiket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='nomor_tiket',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
