# Generated by Django 4.2 on 2026-02-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('pemohon', models.CharField(max_length=150)),
                ('nama_barang', models.CharField(max_length=150)),
                ('kategori', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField(default=1)),
                ('estimasi_harga', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('diterima', 'Barang Datang'), ('selesai', 'Selesai')], default='draft', max_length=20)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
    ]
