# Generated by Django 4.2 on 2026-02-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PengajuanPembelian',
        ),
    ]
