# Generated by Django 4.2 on 2026-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('periode', models.DateField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='laporan/')),
            ],
        ),
    ]
