# Generated by Django 4.2 on 2026-02-14 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lokasi', '0001_initial'),
        ('jaringan', '0003_networklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitKomputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unit', models.CharField(max_length=150)),
                ('hostname', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('sistem_operasi', models.CharField(blank=True, max_length=100)),
                ('spesifikasi', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('maintenance', 'Maintenance'), ('rusak', 'Rusak'), ('nonaktif', 'Non Aktif')], default='aktif', max_length=20)),
                ('tanggal_input', models.DateTimeField(auto_now_add=True)),
                ('pengguna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ruangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lokasi.ruangan')),
                ('terhubung_ke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jaringan.perangkatjaringan')),
            ],
        ),
    ]
