# Generated by Django 4.2 on 2026-02-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerangkatTambahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('monitor', 'Monitor'), ('printer', 'Printer'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('scanner', 'Scanner'), ('lainnya', 'Lainnya')], max_length=30)),
                ('merk', models.CharField(blank=True, max_length=100)),
                ('nomor_seri', models.CharField(blank=True, max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perangkat_tambahan', to='unit.unitkomputer')),
            ],
        ),
    ]
