# Generated by Django 4.2 on 2026-02-16 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_mutasiaset'),
        ('unit', '0002_perangkattambahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='perangkattambahan',
            name='aset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaris.aset'),
        ),
    ]
