# Generated by Django 4.2 on 2026-02-16 01:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_mutasiaset'),
        ('unit', '0003_perangkattambahan_aset'),
    ]

    operations = [
        migrations.AddField(
            model_name='perangkattambahan',
            name='tanggal_pasang',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitkomputer',
            name='aset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_komputer', to='inventaris.aset'),
        ),
        migrations.AlterField(
            model_name='perangkattambahan',
            name='aset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dipasang_di_unit', to='inventaris.aset'),
        ),
        migrations.AlterField(
            model_name='unitkomputer',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.CreateModel(
            name='RiwayatPerangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('dari_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_dari', to='unit.unitkomputer')),
                ('ke_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_ke', to='unit.unitkomputer')),
                ('perangkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit.perangkattambahan')),
            ],
        ),
    ]
