# Generated by Django 4.2 on 2026-02-16 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_mutasiaset'),
        ('unit', '0004_perangkattambahan_tanggal_pasang_unitkomputer_aset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkattambahan',
            name='aset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dipakai_sebagai_perangkat', to='inventaris.aset'),
        ),
        migrations.AlterField(
            model_name='unitkomputer',
            name='aset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dipakai_sebagai_cpu', to='inventaris.aset'),
        ),
    ]
