# Generated by Django 4.2 on 2026-02-20 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventaris', '0002_mutasiaset'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanBulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.DateField()),
                ('total_pembelian', models.IntegerField(default=0)),
                ('total_nominal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('barang_datang', models.IntegerField(default=0)),
                ('barang_verified', models.IntegerField(default=0)),
                ('barang_masuk_inventaris', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Laporan Bulanan',
                'ordering': ['-bulan'],
            },
        ),
        migrations.CreateModel(
            name='SuratPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, unique=True)),
                ('tanggal_pengajuan', models.DateField(auto_now_add=True)),
                ('unit', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Diajukan'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='draft', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kontak', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alamat', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vendor',
            },
        ),
        migrations.CreateModel(
            name='DetailPembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('spesifikasi', models.TextField(blank=True)),
                ('jumlah', models.IntegerField()),
                ('satuan', models.CharField(default='Unit', max_length=50)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('dipesan', 'Dipesan'), ('datang', 'Datang'), ('diverifikasi', 'Diverifikasi'), ('masuk_inventaris', 'Masuk Inventaris')], default='dipesan', max_length=20)),
                ('tanggal_pesan', models.DateField(auto_now_add=True)),
                ('tanggal_datang', models.DateField(blank=True, null=True)),
                ('tanggal_verifikasi', models.DateField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aset_inventaris', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaris.aset')),
                ('surat_pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pembelian', to='pengadaan.suratpengajuan')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pengadaan.vendor')),
            ],
            options={
                'verbose_name_plural': 'Detail Pembelian',
                'ordering': ['-created_at'],
            },
        ),
    ]
