# Generated by Django 4.2 on 2026-02-20 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_mutasiaset'),
        ('pengadaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailSPPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('spesifikasi', models.TextField(blank=True)),
                ('jumlah', models.IntegerField()),
                ('satuan', models.CharField(default='Unit', max_length=50)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aset_inventaris', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventaris.aset')),
            ],
            options={
                'verbose_name_plural': 'Detail SPPB',
            },
        ),
        migrations.CreateModel(
            name='SPPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_sppb', models.CharField(max_length=100, unique=True)),
                ('tanggal_sppb', models.DateField()),
                ('file_sppb', models.FileField(upload_to='pengadaan/sppb/')),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('dipesan', 'Dipesan'), ('datang', 'Datang'), ('diverifikasi', 'Diverifikasi'), ('masuk_inventaris', 'Masuk Inventaris')], default='dipesan', max_length=20)),
                ('tanggal_datang', models.DateField(blank=True, null=True)),
                ('tanggal_verifikasi', models.DateField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pengadaan.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='laporanbulanan',
            old_name='total_pembelian',
            new_name='total_sppb',
        ),
        migrations.DeleteModel(
            name='DetailPembelian',
        ),
        migrations.DeleteModel(
            name='SuratPengajuan',
        ),
        migrations.AddField(
            model_name='detailsppb',
            name='sppb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_barang', to='pengadaan.sppb'),
        ),
    ]
