# Generated by Django 4.2 on 2026-02-20 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pengadaan', '0002_detailsppb_sppb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sppb',
            name='vendor',
        ),
        migrations.AddField(
            model_name='sppb',
            name='unit',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
