# Generated by Django 4.2 on 2026-03-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengadaan', '0004_add_ruangan_sppb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sppb',
            name='file_sppb',
            field=models.FileField(blank=True, null=True, upload_to='pengadaan/sppb/'),
        ),
    ]
