# Generated by Django 4.2 on 2026-01-27 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lokasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerangkatJaringan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('jenis', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('access_point', 'Access Point'), ('server', 'Server'), ('firewall', 'Firewall')], max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('keterangan', models.TextField(blank=True)),
                ('gedung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lokasi.gedung')),
                ('ruangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lokasi.ruangan')),
            ],
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('vlan_id', models.IntegerField()),
                ('subnet', models.CharField(max_length=50)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_port', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('perangkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaringan.perangkatjaringan')),
                ('vlan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jaringan.vlan')),
            ],
        ),
    ]
