# Generated by Django 4.2 on 2026-01-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaringan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perangkatjaringan',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perangkatjaringan',
            name='last_status',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
