# Generated by Django 4.2 on 2026-01-27 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jaringan', '0002_perangkatjaringan_last_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('perangkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaringan.perangkatjaringan')),
            ],
        ),
    ]
