# Generated by Django 4.2 on 2026-01-27 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lokasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_aset', models.CharField(max_length=50, unique=True)),
                ('nama_aset', models.CharField(max_length=150)),
                ('kategori', models.CharField(max_length=100)),
                ('merek', models.CharField(blank=True, max_length=100)),
                ('nomor_seri', models.CharField(blank=True, max_length=100)),
                ('kondisi', models.CharField(max_length=50)),
                ('tanggal_beli', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('barcode', models.ImageField(blank=True, upload_to='barcode/')),
                ('ruangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lokasi.ruangan')),
            ],
        ),
    ]
