# Generated by Django 4.2 on 2026-01-29 02:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0001_initial'),
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutasiAset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.aset')),
                ('dari_ruangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutasi_dari', to='lokasi.ruangan')),
                ('ke_ruangan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutasi_ke', to='lokasi.ruangan')),
            ],
        ),
    ]
