# Generated by Django 4.2 on 2026-03-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_mutasiaset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aset',
            name='kondisi',
            field=models.CharField(choices=[('Baik', 'Baik'), ('Rusak', 'Rusak'), ('Maintenance', 'Maintenance'), ('Baru', 'Baru')], default='Baik', max_length=50),
        ),
    ]
