# Generated by Django 4.2 on 2026-01-27 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermintaanBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('delivered', 'Dikirim')], default='pending', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.consumable')),
                ('peminta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
