# Generated by Django 4.2 on 2026-01-27 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPerbaikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('masalah', models.TextField()),
                ('tindakan', models.TextField()),
                ('biaya', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.aset')),
                ('teknisi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPemeliharaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('rutin', 'Rutin'), ('insidental', 'Insidental')], max_length=20)),
                ('tanggal_jadwal', models.DateField()),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(default='terjadwal', max_length=30)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.aset')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
