# Generated by Django 4.2 on 2026-01-27 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=150)),
                ('kategori', models.CharField(max_length=100)),
                ('stok', models.IntegerField(default=0)),
                ('satuan', models.CharField(max_length=50)),
                ('batas_minimum', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=150)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PengeluaranConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.consumable')),
                ('digunakan_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consumable',
            name='gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gudang.gudang'),
        ),
    ]
