# Generated by Django 4.2 on 2026-03-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lokasi', '0001_initial'),
        ('gudang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengeluaranconsumable',
            name='ruangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lokasi.ruangan'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='kategori',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='satuan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
